apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bookstack.fullname" . }}
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
data:
{{- with .Values.database }}
  DB_HOST: {{ .host | b64enc }}
  DB_PORT: {{ (.port | default "3306") | toString | b64enc }}
  DB_USER: {{ .user | b64enc }}
  DB_DATABASE: {{ .name | b64enc }}
{{- end }}
{{- with .Values.customSecrets }}
  {{- if .databasePassword }}
  DB_PASSWORD: {{ .databasePassword | b64enc }}
  {{- end }}
  {{- if .smtpUser }}
  MAIL_USERNAME: {{ .smtpUser | b64enc }}
  {{- end }}
  {{- if .smtpPassword }}
  MAIL_PASSWORD: {{ .smtpPassword | b64enc }}
  {{- end }}
{{- end }}
