{{- if not .Values.config.github.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "gitlab-matrix-project-bot.fullname" . }}-github"
  labels:
    {{- include "gitlab-matrix-project-bot.labels" . | nindent 4 }}
type: Opaque
data:
  GH_USER: "{{ .Values.config.github.token | b64enc }}"
  GH_TOKEN: "{{ .Values.config.github.token | b64enc }}"
{{- end }}