{{- if not .Values.config.matrix.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "github-matrix-project-bot.fullname" . }}-matrix"
  labels:
    {{- include "github-matrix-project-bot.labels" . | nindent 4 }}
type: Opaque
data:
  MX_URL: "{{ .Values.config.matrix.url | b64enc }}"
  MX_TOKEN: "{{ .Values.config.matrix.token | b64enc }}"
{{- end }}