{{- if .Values.customSecrets }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "ghost.fullname" . }}-custom-secrets
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.customSecrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
